### PR TITLE
added first draft of D2L instructions

### PR DESCRIPTION
**Pull request by DavidCooperWCU**
This is a first draft of the instructions. I'm not sure if all of the formatting is right, and I could add screen shots, but since the other LMS descriptions don't include screenshots, I didn't want the style to be that different.

I'm also not sure if any formatting, like bold or italics can be added to the \<pre\> selections, since in html they can't. 

Please let me know if I need to make any changes so that this can be added.

### CODE REVIEW

**Comment by bnmnetp** [comment]
Thanks @DavidCooperWCU

**Comment by DavidCooperWCU** [comment]
It looks like the subsection isn’t in the right spot. The numbering is wrong, and the Brightspace D2L doesn’t show up in the table of contents with canvas and moodle.

**Comment by DavidCooperWCU** [comment]
This line should move from

https://github.com/RunestoneInteractive/InstructorGuide/blob/105eb1faa706ff6db136b01cf05c79753172e340/pretext/Registration/lti.ptx#L117

to in between here:

https://github.com/RunestoneInteractive/InstructorGuide/blob/105eb1faa706ff6db136b01cf05c79753172e340/pretext/Registration/lti.ptx#L177-L178

**Comment by bnmnetp** [comment]
If you `pip install pretext` you can `pretext build` and then `pretext view` your changes.

**Pull request merged**
